name: Build and Release ECT Technis Electron App

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Get version
      id: get_version
      run: |
        if (Test-Path version.txt) {
          $version = Get-Content version.txt -Raw
          $version = $version.Trim()
        } else {
          $version = "1.1.0"
        }
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        
        # Update package.json version
        $packageJson = Get-Content -Path package.json -Raw | ConvertFrom-Json
        $packageJson.version = $version
        $packageJson | ConvertTo-Json -Depth 100 | Set-Content -Path package.json
    
    - name: Check if tag exists
      id: check_tag
      run: |
        $tagExists = git tag -l "v${{ steps.get_version.outputs.VERSION }}"
        if ("$tagExists" -eq "v${{ steps.get_version.outputs.VERSION }}") {
          echo "TAG_EXISTS=true" >> $env:GITHUB_OUTPUT
        } else {
          echo "TAG_EXISTS=false" >> $env:GITHUB_OUTPUT
        }
    
    - name: Install dependencies
      run: |
        # Python dependencies
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        # Node.js dependencies
        npm install --legacy-peer-deps
        npm install -g electron-builder
    
    - name: Create CHANGELOG if missing
      run: |
        if (!(Test-Path "CHANGELOG.md")) {
          @"
        # Changelog
        
        ## v${{ steps.get_version.outputs.VERSION }}
        
        ### Features
        - Excel file comparison tool with advanced matching algorithms
        - Dynamic header detection for flexible file structures  
        - Multiple comparison modes (full, quick, custom)
        - Comprehensive report generation (Excel, CSV, PDF formats)
        - Site mapping and configuration management
        - Real-time comparison progress tracking
        
        ### Technical
        - Built with Electron + Flask architecture
        - Python backend with pandas/openpyxl for Excel processing
        - Modern HTML5/CSS3/JavaScript frontend
        - Windows x64 native application
        - Portable and installer distribution options
        - No external dependencies required
        
        ### Installation
        - **ECT_Technis_Setup_v${{ steps.get_version.outputs.VERSION }}.exe**: Full installer with shortcuts
        - **ECT_Technis_Portable_v${{ steps.get_version.outputs.VERSION }}.exe**: Portable version, no installation needed
        
        ### System Requirements  
        - Windows 10/11 (x64)
        - 4GB RAM recommended
        - 100MB free disk space
        "@ | Set-Content -Path "CHANGELOG.md"
          Write-Host "CHANGELOG.md created"
        } else {
          Write-Host "CHANGELOG.md already exists"
        }
    
    - name: Verify source files exist
      run: |
        $requiredFiles = @(
          "src/backend/app.py",
          "src/electron/main.js", 
          "src/electron/preload.js"
          "src/frontend/index.html",
          "src/frontend/images/icon_excel_comparison.ico",
          "package.json",
          "requirements.txt"
        )
        
        $missingFiles = @()
        foreach ($file in $requiredFiles) {
          if (!(Test-Path $file)) {
            $missingFiles += $file
            Write-Warning "Missing required file: $file"
          }
        }
        
        if ($missingFiles.Count -gt 0) {
          Write-Error "Build cannot continue - missing required files: $($missingFiles -join ', ')"
          exit 1
        }
        Write-Host "All required files found ✓"
    
    - name: Prepare secure build
      run: |
        Write-Host "Using original src directory structure..."
        
        # Just verify files exist
        $criticalFiles = @(
          "src\backend\app.py",
          "src\electron\main.js",
          "src\electron\preload.js",
          "src\frontend\index.html",
          "src\frontend\images\icon_excel_comparison.ico"
        )
        
        foreach ($file in $criticalFiles) {
          if (!(Test-Path $file)) {
            Write-Error "Critical file not found: $file"
            exit 1
          }
        }
        Write-Host "All critical files verified ✓"

    - name: Update package.json for build
      run: |
        # No changes needed - keep original paths
        Write-Host "Using original package.json configuration ✓"
    
    - name: Build Python backend with PyInstaller
      run: |
        Write-Host "Building Python backend executable..."
        pip install pyinstaller
        
        # Create resources directory if it doesn't exist
        if (!(Test-Path "resources/backend")) {
          New-Item -ItemType Directory -Path "resources/backend" -Force
        }
        
        # Get current directory - all paths will be relative to this
        $currentDir = Get-Location
        Write-Host "Working directory: $currentDir"
        
        # Create necessary directories if they don't exist
        foreach ($dir in @("src/core", "src/utils", "src/models")) {
          if (!(Test-Path $dir)) {
            Write-Host "Creating directory $dir"
            New-Item -ItemType Directory -Path $dir -Force
            # Create __init__.py to make it a valid package
            Set-Content -Path "$dir/__init__.py" -Value "# Package initialization"
          }
        }
        
        # First check if app.py exists
        if (!(Test-Path "src/backend/app.py")) {
          Write-Error "src/backend/app.py not found!"
          exit 1
        }
        
        # Run PyInstaller
        Write-Host "Running PyInstaller..."

        # Create a temporary directory to organize modules properly
        $tempModuleDir = "temp_modules"
        if (Test-Path $tempModuleDir) { Remove-Item $tempModuleDir -Recurse -Force }
        New-Item -ItemType Directory -Path $tempModuleDir -Force

        # Copy files with proper structure
        Copy-Item "src/utils/config.py" "$tempModuleDir/"
        Copy-Item "src/core/comparison_engine.py" "$tempModuleDir/"
        Copy-Item "src/core/excel_processor.py" "$tempModuleDir/"
        Copy-Item "src/core/site_matcher.py" "$tempModuleDir/"
        Copy-Item "src/core/report_generating.py" "$tempModuleDir/"
        Copy-Item "src/core/analysis.py" "$tempModuleDir/"
        Copy-Item "src/models/data_models.py" "$tempModuleDir/"

        # Create __init__.py files to make them proper packages
        Set-Content -Path "$tempModuleDir/__init__.py" -Value ""

        # Now run PyInstaller with the organized modules
        pyinstaller --onefile --windowed --name=ect-backend --distpath=dist/backend --workpath=build/pyinstaller `
        --paths=$tempModuleDir `
        src/backend/app.py `
        --add-data "docs;docs" `
        --add-data "$tempModuleDir;." `
        --hidden-import=flask `
        --hidden-import=flask_cors `
        --hidden-import=pandas `
        --hidden-import=numpy `
        --hidden-import=openpyxl `
        --hidden-import=werkzeug `
        --hidden-import=dateutil.parser `
        --hidden-import=tempfile `
        --hidden-import=io `
        --hidden-import=shutil `
        --hidden-import=xlsxwriter.workbook `
        --hidden-import=reportlab.lib.pagesizes `
        --hidden-import=reportlab.pdfgen `
        --hidden-import=reportlab.platypus `
        --hidden-import=pandas.io.formats.excel `
        --hidden-import=openpyxl.worksheet._writer `

        # Clean up temporary directory
        Remove-Item $tempModuleDir -Recurse -Force
        
        # Verify the executable was created
        if (Test-Path "dist/backend/ect-backend.exe") {
          Write-Host "✓ Python backend executable created successfully"
          $backendSize = (Get-Item "dist/backend/ect-backend.exe").Length / 1MB
          Write-Host "  Size: $([math]::Round($backendSize, 2)) MB"
          
          # Skip the help test since it might not be implemented
          
          # Copy the executable to the resources folder
          Copy-Item "dist/backend/ect-backend.exe" "resources/backend/"
          Write-Host "✓ Backend executable copied to resources"
        } else {
          Write-Error "Failed to create Python backend executable"
          
          # List PyInstaller output files for debugging
          Write-Host "Checking build directory contents:"
          if (Test-Path "build/pyinstaller") {
            Get-ChildItem -Path "build/pyinstaller" -Filter "warn-*" | ForEach-Object {
              Write-Host "--- $($_.Name) ---"
              Get-Content $_.FullName
            }
          }
          
          exit 1
        }

    - name: Build Electron app
      run: |
        Write-Host "Building Electron application..."
        
        # Verify backend executable exists before building
        if (!(Test-Path "resources/backend/ect-backend.exe")) {
          Write-Error "Backend executable not found. PyInstaller step may have failed."
          exit 1
        }
        
        # Build both installer and portable versions
        npx electron-builder --win --x64 --publish=never
        
        # Verify build outputs
        if (Test-Path "dist") {
          Write-Host "`nBuild artifacts created:"
          Get-ChildItem -Path dist -Filter "*.exe" | ForEach-Object {
            $sizeInMB = [math]::Round($_.Length / 1MB, 2)
            Write-Host "  ✓ $($_.Name) - Size: $sizeInMB MB"
          }
        } else {
          Write-Error "Build failed - no dist folder created"
          exit 1
        }
    
    - name: Restore original package.json
      run: |
        if (Test-Path "package-original.json") {
          Copy-Item package-original.json package.json -Force
          Remove-Item package-original.json
          Write-Host "Original package.json restored ✓"
        }
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ECT_Technis_v${{ steps.get_version.outputs.VERSION }}
        path: |
          dist/*.exe
        retention-days: 90
    
    - name: Create and push tag if needed
      if: steps.check_tag.outputs.TAG_EXISTS == 'false' && github.event_name != 'workflow_dispatch'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a v${{ steps.get_version.outputs.VERSION }} -m "Release version ${{ steps.get_version.outputs.VERSION }}"
        git push origin v${{ steps.get_version.outputs.VERSION }}

    - name: Create GitHub Release
      if: steps.check_tag.outputs.TAG_EXISTS == 'false'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        files: |
          dist/*.exe
        name: ECT Technis v${{ steps.get_version.outputs.VERSION }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}