name: Build and Release Excel Comparison Tool

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install 2to3
        # Install pyminifier
        pip install pyminifier

        # Verify installation
        python -c "import pyminifier" || (echo 'Failed to install pyminifier' && exit 1)
        pip install -r requirements.txt
    
    - name: Get version from file
      id: get_version
      run: |
        if (Test-Path version.txt) {
          $version = Get-Content version.txt -Raw
          $version = $version.Trim()
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        } else {
          # Get version from git tag or default
          $gitTag = git describe --tags --exact-match 2>$null
          if ($gitTag) {
            $version = $gitTag -replace '^v', ''
          } else {
            $version = "1.0.0"
          }
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        }
    
    - name: Check if tag exists
      id: check_tag
      run: |
        $tagExists = git tag -l "v${{ steps.get_version.outputs.VERSION }}"
        if ("$tagExists" -eq "v${{ steps.get_version.outputs.VERSION }}") {
          echo "TAG_EXISTS=true" >> $env:GITHUB_OUTPUT
        } else {
          echo "TAG_EXISTS=false" >> $env:GITHUB_OUTPUT
        }
    
    - name: Verify project structure
      run: |
        # Verify entry point exists
        if (Test-Path src/backend/app.py) {
          echo "Entry point src/backend/app.py exists"
        } else {
          echo "Entry point src/backend/app.py does not exist"
          Get-ChildItem -Path . -Recurse -Filter "*.py" | Select-Object FullName
          exit 1
        }
        
        # List project structure for debugging
        echo "Project structure:"
        Get-ChildItem -Path . -Recurse | Where-Object { $_.Name -match '\.(py|txt|md)$' } | Select-Object FullName

    - name: Secure code with basic obfuscation
      run: |
        # Create build directory structure
        New-Item -Path "secure_build" -ItemType Directory -Force
        New-Item -Path "secure_build/src" -ItemType Directory -Force
        New-Item -Path "secure_build/src/backend" -ItemType Directory -Force
        New-Item -Path "secure_build/src/core" -ItemType Directory -Force
        New-Item -Path "secure_build/src/models" -ItemType Directory -Force
        New-Item -Path "secure_build/src/utils" -ItemType Directory -Force
        
        # Install Python code transformation tools
        pip install pyminifier
        
        # Apply basic code obfuscation to Python files
        Get-ChildItem -Path "src" -Filter "*.py" -Recurse | ForEach-Object {
          $relativePath = $_.FullName.Substring((Get-Location).Path.Length + 1)
          $outputPath = Join-Path "secure_build" $relativePath
          $outputDir = Split-Path -Path $outputPath -Parent
          
          # Ensure output directory exists
          if (-not (Test-Path $outputDir)) {
            New-Item -Path $outputDir -ItemType Directory -Force | Out-Null
          }
          
          # Apply obfuscation using pyminifier
          Write-Host "Securing: $relativePath"
          python -m pyminifier --obfuscate-variables --obfuscate-functions --replacement-length=3 $_.FullName | Out-File -FilePath $outputPath -Encoding utf8
        }
        
        # Copy non-Python files (keeping directory structure)
        Get-ChildItem -Path "src" -Recurse | Where-Object { -not $_.PSIsContainer -and $_.Extension -ne ".py" } | ForEach-Object {
          $relativePath = $_.FullName.Substring((Get-Location).Path.Length + 1)
          $outputPath = Join-Path "secure_build" $relativePath
          $outputDir = Split-Path -Path $outputPath -Parent
          
          # Ensure output directory exists
          if (-not (Test-Path $outputDir)) {
            New-Item -Path $outputDir -ItemType Directory -Force | Out-Null
          }
          
          # Copy the file
          Copy-Item -Path $_.FullName -Destination $outputPath -Force
        }
        
        # Copy frontend files
        if (Test-Path "src/frontend") {
          Copy-Item -Path "src/frontend" -Destination "secure_build/src/" -Recurse -Force
          echo "Frontend files copied to secure_build/src/frontend"
        }
        
        # Copy docs directory if it exists
        if (Test-Path "docs") {
          Copy-Item -Path "docs" -Destination "secure_build/" -Recurse -Force
          echo "Docs copied to secure_build/docs"
        }
        
        # Verify build was successful
        if (Test-Path "secure_build/src/backend/app.py") {
          echo "Code transformation successful"
        } else {
          echo "Code transformation failed"
          exit 1
        }

    - name: Build executable with PyInstaller
      run: |
        # Find icon file
        $iconParam = ""
        if (Test-Path "src/frontend/images/icon_excel_comparison.ico") {
          $iconParam = "--icon=src/frontend/images/icon_excel_comparison.ico"
          echo "Using icon from: src/frontend/images/icon_excel_comparison.ico"
        } else {
          echo "No icon file found"
        }
        
        # Build with PyInstaller (with --key for additional security)
        $version = "${{ steps.get_version.outputs.VERSION }}"
        $randomKey = [System.Guid]::NewGuid().ToString().Substring(0, 16)
        
        python -m PyInstaller --onefile --windowed $iconParam `
          --key=$randomKey `
          --name "ECT_Technis_v$version" `
          --add-data "secure_build/src/frontend;src/frontend" `
          --add-data "secure_build/docs;docs" `
          --add-data "version.txt;." `
          --hidden-import "flask" `
          --hidden-import "flask_cors" `
          --hidden-import "pandas" `
          --hidden-import "openpyxl" `
          --hidden-import "xlsxwriter" `
          --hidden-import "werkzeug" `
          --hidden-import "numpy" `
          --paths="secure_build" `
          --clean `
          secure_build/src/backend/app.py
        
        # Verify the build
        if (Test-Path "dist/ECT_Technis_v$version.exe") {
          echo "Build successful"
        } else {
          echo "Build failed - executable not found"
          Get-ChildItem -Path "dist" -ErrorAction SilentlyContinue
          exit 1
        }
        
    - name: Test executable
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        # Basic test to ensure the executable can start
        $proc = Start-Process -FilePath "dist/ECT_Technis_v$version.exe" -PassThru -WindowStyle Hidden
        Start-Sleep -Seconds 10
        if (-not $proc.HasExited) {
          Stop-Process -Id $proc.Id -Force
          echo "Executable test passed - application started successfully"
        } else {
          echo "Warning: Executable exited quickly - may have issues"
          # Don't fail the build for this warning
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ECT_Technis_v${{ steps.get_version.outputs.VERSION }}
        path: |
          dist/ECT_Technis_v${{ steps.get_version.outputs.VERSION }}.exe
        retention-days: 90
    
    - name: Create and push tag if needed
      if: steps.check_tag.outputs.TAG_EXISTS == 'false' && github.event_name != 'workflow_dispatch'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a v${{ steps.get_version.outputs.VERSION }} -m "Release version ${{ steps.get_version.outputs.VERSION }}"
        git push origin v${{ steps.get_version.outputs.VERSION }}

    - name: Generate release notes if missing
      if: steps.check_tag.outputs.TAG_EXISTS == 'false'
      run: |
        if (!(Test-Path RELEASE_NOTES.md)) {
          $version = "${{ steps.get_version.outputs.VERSION }}"
          echo "# ECT Technis v$version" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## What's New" >> RELEASE_NOTES.md
          echo "- Updated to version $version" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## Installation" >> RELEASE_NOTES.md
          echo "1. Download the executable file" >> RELEASE_NOTES.md
          echo "2. Run ECT_Technis_v$version.exe" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## System Requirements" >> RELEASE_NOTES.md
          echo "- Windows 10 or later" >> RELEASE_NOTES.md
          echo "- No additional installation required" >> RELEASE_NOTES.md
        }

    - name: Create GitHub Release
      if: steps.check_tag.outputs.TAG_EXISTS == 'false'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        files: |
          dist/ECT_Technis_v${{ steps.get_version.outputs.VERSION }}.exe
        name: ECT Technis v${{ steps.get_version.outputs.VERSION }}
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload debug artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-artifacts-${{ steps.get_version.outputs.VERSION }}
        path: |
          dist_obf/
          build/
          *.spec
          *.log
        retention-days: 7